project:
  type: website
  title: "Julia Machine Learning"
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "data/iris.csv"
    
website:
  title: "Machine-Learning Julia"
  navbar:
    logo:  imgs/logo.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: start/index.qmd
        text: "Start"
      - href:  workflow/index.qmd
        text: "Workflow"
      - href: packages/index.qmd
        text: "Packages"
      - href: learn/index.qmd
        text: "Learn"
      - href: dataset/index.qmd
        text: "Dataset"
      - text: "More"
        menu:
          - about.qmd
          - reference.qmd 
  sidebar:
    - id: get-started
      style: "floating"
      contents:
        - text: "GET STARTED"
          href:  start/index.qmd
        - text: "build first model"
          href: start/getting-start.qmd
          
    - id: learn
      collapse-level: 1
      contents:
        - text: "Learn"
          href: learn/index.qmd 
        - text: "ensemble model"
          href: learn/ensemble-model.qmd 
        - text: "ensemble model with boston housing dataset"
          href: learn/ensemblemodel-with-bostonhouse.qmd
        - text: "learnig network 1"
          href: learn/learning-network-1.qmd 
        - text: "tailwind css test"
          href: learn/tailwind-test.qmd 
        - text: "PCA  explained"
          href: learn/pca-explained.qmd 
        - text: "menu test"
        - href: learn/menu-test.qmd
        - text: "Iris Pipeline"
        - href: learn/iris-pipeline.qmd
        - text: "Digits pca kmeans"
        - href: learn/digits-kmeans.qmd

    - id: packages
      collapse-level: 1
      contents:
        - text: "Julia Machine Learning Package Intro"
        - href: packages/index.qmd
        - text: "GLM.jl homepage"
          href: packages/glm.qmd 
    - id: workflow
      collapse-level: 1
      contents:
        - text: "flowchart"
          href:  workflow/index.qmd 
        - text: "composing models"
          href:  workflow/composing-models.qmd 
        - text: "mlj cheatsheet"
          href:  workflow/mlj-cheatsheet.qmd
        - text: "MLJ PCA Workflow"
          href:  workflow/mlj-pca-workflow.qmd
    - id: regression
      collapse-level: 1
      contents:  
        - text: "Regression Intro"
          href: learn/Regression/index.qmd
        - text:  "1.Cricket Chirps Rate"
          href:  learn/Regression/1-cricket-chirps.qmd
        - text:  "2.FloridaLakes"
          href:  learn/Regression/2-florida-lakes.qmd
        - text:  "3-gaussian-mixturemodels-regression(boston housing)"
          href:  learn/Regression/3-gaussian-mixturemodels-regression.qmd
        - text:  "4-salary-dataset-linear-regression"
          href:  learn/Regression/4-salary-linear-regression.qmd
        - text:  "5-ecommerce-customer-dataset-linear-regression"
          href:  learn/Regression/5-ecommerce-dataset-linear-regression.qmd

    - id: classfication
      collapse-level: 1
      contents:  
        - text: "Classfication Intro"
          href:  learn/Classfication/index.qmd 
        - text: "1-Diabetes Catboost Classification"
          href: learn/Classfication/1-diabetes-catboost-classification.qmd
        - text: "2-mnist-classification"
          href:  learn/Classfication/2-mnist-classification.qmd 
        - text: "3-iris-logistics-classification"
          href:  learn/Classfication/3-iris-logistics-classification.qmd 
        - text: "4-basic1-classification(catboost)"
          href:  learn/Classfication/4-catboost-classification-basic.qmd
        
    - id: clustering
      collapse-level: 1
      contents:  
        - text: "Clustering Intro"
          href:  learn/Clustering/index.qmd
        - text: "1-IRIS PCA-Kmeans clustering"
          href:  learn/Clustering/1-iris-pca-kmeans.qmd
        - text: "2-IRIS KernelPCA-Kmeans clustering"
          href:  learn/Clustering/2-iris-kernelpca-kmeans.qmd
        - text: "3-Kmeans clustering on Digits"
          href:  learn/Clustering/3-kmeans-on-digits.qmd
        
    - id: dimensionreduction
      collapse-level: 1
      contents:  
        - text: "Dimensionreduction Intro"
          href:  learn/Dimension/index.qmd
        - text: "1.NIR Spectra of Milk"
          href:  learn/Dimension/1-nir-spectra-milk.qmd
        - text: "3.IRIS  PCA "
          href:  learn/Dimension/3-iris-pca.qmd 
        - text: "4.Mnist  PCA "
          href:  learn/Dimension/4-mnist-pca.qmd 
        - text: "5. texture  PCA "
          href:  learn/Dimension/5-texture-pca.qmd
    - id: ensemble
      collapse-level: 1
      contents:  
        - text: "Ensemble  Intro"
          href:  learn/Ensemble/index.qmd 
    - id: learning-network
      collapse-level: 1
      contents:  
        - text: "Learning Network  Intro"
          href:  learn/LearningNetwork/index.qmd
    
    
    - id: dataset
      collapse-level: 1
      contents:
        - text: "intro"
          href: dataset/index.qmd 
        - text: "1.iris"
          href: dataset/iris.qmd 
        - text: "2.penguins"
          href: dataset/penguins.qmd 
        - text: "3.boston housing"
          href: dataset/boston-house.qmd
        - text: "4.auto mpg"
          href: dataset/mtcar.qmd
        - text: "5.penguins dashboard"
          href: dataset/penguins-dahboard.qmd
        - text: "6.telecom customer churn"
          href: dataset/telecom-churn.qmd
        - text: "7.breast cancer"
          href: dataset/breast-cancer.qmd
        - text: "8.Diabetes diagnosis dataset"
          href: dataset/diabetes.qmd
        - text: "9.Diamonds dataset"
          href: dataset/diamond.qmd
        - text: "10.Circket chirps rate"
          href: dataset/circket-chirps.qmd 
        - text: "11.Florida Lakes Dataset"
          href: dataset/florida-lakes.qmd
        - text: "12.Ecommerce Customer dataset"
          href: dataset/ecommerce-customer-dataset.qmd
        - text: "13. German Credit Card dataset"
          href: dataset/german-credit-card.qmd
        - text: "14 clustering datset(kaggle)"
          href: dataset/clustering-dataset.qmd
      
        
    
format:
  html:
    quarto-required: ">= 1.3.353"
    toc: true
    linestretch: 1.6
    grid:
      body-width: 840px
    mermaid:
      theme: forest
    code-block-bg: true
    code-block-border-left: "#ff0000"
     
theme:
  - cosmo
  -  styles.scss
  -  theme.css
  -  feaures.css
  #- components.min.scss
execute:
  freeze: auto
  keep-md: false

filters:
  - _extensions/qreacto/qreacto.lua

code-block-bg: true
highlight-style: Ayu 