project:
  type: website
  title: "Julia Machine Learning"
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "data/iris.csv"
    
website:
  title: "Machine-Learning Julia"
  navbar:
    logo:  imgs/logo.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: start/index.qmd
        text: "Start"
      - href:  workflow/index.qmd
        text: "Workflow"
      - href: packages/index.qmd
        text: "Packages"
      - href: learn/index.qmd
        text: "Learn"
      - href: dataset/index.qmd
        text: "Dataset"
      - text: "More"
        menu:
          - about.qmd
          - reference.qmd 
  sidebar:
    - id: get-started
      style: "floating"
      contents:
        - text: "GET STARTED"
          href:  start/index.qmd
        - text: "build first model"
          href: start/getting-start.qmd
          
    - id: learn
      collapse-level: 1
      contents:
        - text: "Learn"
          href: learn/index.qmd 
        - text: "ensemble model"
          href: learn/ensemble-model.qmd 
        - text: "ensemble model with boston housing dataset"
          href: learn/ensemblemodel-with-bostonhouse.qmd
        - text: "learnig network 1"
          href: learn/learning-network-1.qmd 
        - text: "tailwind css test"
          href: learn/tailwind-test.qmd 
        - text: "PCA  explained"
          href: learn/pca-explained.qmd 
        - text: "menu test"
        - href: learn/menu-test.qmd
    - id: packages
      collapse-level: 1
      contents:
        - text: "GLM"
          href: packages/glm.qmd 
    - id: workflow
      collapse-level: 1
      contents:
        - text: "flowchart"
          href:  workflow/index.qmd 
        - text: "composing models"
          href:  workflow/composing-models.qmd 
        - text: "mlj cheatsheet"
          href:  workflow/mlj-cheatsheet.qmd
    - id: dataset
      collapse-level: 1
      contents:
        - text: "intro"
          href: dataset/index.qmd 
        - text: "1.iris"
          href: dataset/iris.qmd 
        - text: "2.penguins"
          href: dataset/penguins.qmd 
        - text: "3.boston housing"
          href: dataset/boston-house.qmd
        - text: "4.auto mpg"
          href: dataset/mtcar.qmd
        - text: "5.penguins dashboard"
          href: dataset/penguins-dahboard.qmd
    
format:
  html:
    quarto-required: ">= 1.3.353"
    toc: true
    linestretch: 1.6
    grid:
      body-width: 840px
    mermaid:
      theme: forest
     
theme:
  - cosmo
  -  styles.scss
  -  theme.css
  -  feaures.css
  #- components.min.scss
execute:
  freeze: auto
  keep-md: false

filters:
  - _extensions/qreacto/qreacto.lua

code-block-bg: true
highlight-style: Ayu 